export type PeriodicBlock = "s" | "p" | "d" | "f";

export type PeriodicCategory =
  | "nonmetal"
  | "noble-gas"
  | "alkaline"
  | "alkaline-earth"
  | "post-transition"
  | "metalloid"
  | "halogen"
  | "transition"
  | "lanthanide"
  | "actinide";

export type PeriodicElement = {
  symbol: string;
  name: string;
  category: PeriodicCategory;
  block: PeriodicBlock;
  row: number;
  col: number;
};

export const elements: PeriodicElement[] = [
  // Period 1
  {
    symbol: "H",
    name: "Hydrogen",
    category: "nonmetal",
    block: "s",
    row: 1,
    col: 1,
  },
  {
    symbol: "He",
    name: "Helium",
    category: "noble-gas",
    block: "p",
    row: 1,
    col: 18,
  },
  // Period 2
  {
    symbol: "Li",
    name: "Lithium",
    category: "alkaline",
    block: "s",
    row: 2,
    col: 1,
  },
  {
    symbol: "Be",
    name: "Beryllium",
    category: "alkaline-earth",
    block: "s",
    row: 2,
    col: 2,
  },
  {
    symbol: "B",
    name: "Boron",
    category: "metalloid",
    block: "p",
    row: 2,
    col: 13,
  },
  {
    symbol: "C",
    name: "Carbon",
    category: "nonmetal",
    block: "p",
    row: 2,
    col: 14,
  },
  {
    symbol: "N",
    name: "Nitrogen",
    category: "nonmetal",
    block: "p",
    row: 2,
    col: 15,
  },
  {
    symbol: "O",
    name: "Oxygen",
    category: "nonmetal",
    block: "p",
    row: 2,
    col: 16,
  },
  {
    symbol: "F",
    name: "Fluorine",
    category: "halogen",
    block: "p",
    row: 2,
    col: 17,
  },
  {
    symbol: "Ne",
    name: "Neon",
    category: "noble-gas",
    block: "p",
    row: 2,
    col: 18,
  },
  // Period 3
  {
    symbol: "Na",
    name: "Sodium",
    category: "alkaline",
    block: "s",
    row: 3,
    col: 1,
  },
  {
    symbol: "Mg",
    name: "Magnesium",
    category: "alkaline-earth",
    block: "s",
    row: 3,
    col: 2,
  },
  {
    symbol: "Al",
    name: "Aluminium",
    category: "post-transition",
    block: "p",
    row: 3,
    col: 13,
  },
  {
    symbol: "Si",
    name: "Silicon",
    category: "metalloid",
    block: "p",
    row: 3,
    col: 14,
  },
  {
    symbol: "P",
    name: "Phosphorus",
    category: "nonmetal",
    block: "p",
    row: 3,
    col: 15,
  },
  {
    symbol: "S",
    name: "Sulfur",
    category: "nonmetal",
    block: "p",
    row: 3,
    col: 16,
  },
  {
    symbol: "Cl",
    name: "Chlorine",
    category: "halogen",
    block: "p",
    row: 3,
    col: 17,
  },
  {
    symbol: "Ar",
    name: "Argon",
    category: "noble-gas",
    block: "p",
    row: 3,
    col: 18,
  },
  // Period 4
  {
    symbol: "K",
    name: "Potassium",
    category: "alkaline",
    block: "s",
    row: 4,
    col: 1,
  },
  {
    symbol: "Ca",
    name: "Calcium",
    category: "alkaline-earth",
    block: "s",
    row: 4,
    col: 2,
  },
  {
    symbol: "Sc",
    name: "Scandium",
    category: "transition",
    block: "d",
    row: 4,
    col: 3,
  },
  {
    symbol: "Ti",
    name: "Titanium",
    category: "transition",
    block: "d",
    row: 4,
    col: 4,
  },
  {
    symbol: "V",
    name: "Vanadium",
    category: "transition",
    block: "d",
    row: 4,
    col: 5,
  },
  {
    symbol: "Cr",
    name: "Chromium",
    category: "transition",
    block: "d",
    row: 4,
    col: 6,
  },
  {
    symbol: "Mn",
    name: "Manganese",
    category: "transition",
    block: "d",
    row: 4,
    col: 7,
  },
  {
    symbol: "Fe",
    name: "Iron",
    category: "transition",
    block: "d",
    row: 4,
    col: 8,
  },
  {
    symbol: "Co",
    name: "Cobalt",
    category: "transition",
    block: "d",
    row: 4,
    col: 9,
  },
  {
    symbol: "Ni",
    name: "Nickel",
    category: "transition",
    block: "d",
    row: 4,
    col: 10,
  },
  {
    symbol: "Cu",
    name: "Copper",
    category: "transition",
    block: "d",
    row: 4,
    col: 11,
  },
  {
    symbol: "Zn",
    name: "Zinc",
    category: "transition",
    block: "d",
    row: 4,
    col: 12,
  },
  {
    symbol: "Ga",
    name: "Gallium",
    category: "post-transition",
    block: "p",
    row: 4,
    col: 13,
  },
  {
    symbol: "Ge",
    name: "Germanium",
    category: "metalloid",
    block: "p",
    row: 4,
    col: 14,
  },
  {
    symbol: "As",
    name: "Arsenic",
    category: "metalloid",
    block: "p",
    row: 4,
    col: 15,
  },
  {
    symbol: "Se",
    name: "Selenium",
    category: "nonmetal",
    block: "p",
    row: 4,
    col: 16,
  },
  {
    symbol: "Br",
    name: "Bromine",
    category: "halogen",
    block: "p",
    row: 4,
    col: 17,
  },
  {
    symbol: "Kr",
    name: "Krypton",
    category: "noble-gas",
    block: "p",
    row: 4,
    col: 18,
  },
  // Period 5
  {
    symbol: "Rb",
    name: "Rubidium",
    category: "alkaline",
    block: "s",
    row: 5,
    col: 1,
  },
  {
    symbol: "Sr",
    name: "Strontium",
    category: "alkaline-earth",
    block: "s",
    row: 5,
    col: 2,
  },
  {
    symbol: "Y",
    name: "Yttrium",
    category: "transition",
    block: "d",
    row: 5,
    col: 3,
  },
  {
    symbol: "Zr",
    name: "Zirconium",
    category: "transition",
    block: "d",
    row: 5,
    col: 4,
  },
  {
    symbol: "Nb",
    name: "Niobium",
    category: "transition",
    block: "d",
    row: 5,
    col: 5,
  },
  {
    symbol: "Mo",
    name: "Molybdenum",
    category: "transition",
    block: "d",
    row: 5,
    col: 6,
  },
  {
    symbol: "Tc",
    name: "Technetium",
    category: "transition",
    block: "d",
    row: 5,
    col: 7,
  },
  {
    symbol: "Ru",
    name: "Ruthenium",
    category: "transition",
    block: "d",
    row: 5,
    col: 8,
  },
  {
    symbol: "Rh",
    name: "Rhodium",
    category: "transition",
    block: "d",
    row: 5,
    col: 9,
  },
  {
    symbol: "Pd",
    name: "Palladium",
    category: "transition",
    block: "d",
    row: 5,
    col: 10,
  },
  {
    symbol: "Ag",
    name: "Silver",
    category: "transition",
    block: "d",
    row: 5,
    col: 11,
  },
  {
    symbol: "Cd",
    name: "Cadmium",
    category: "transition",
    block: "d",
    row: 5,
    col: 12,
  },
  {
    symbol: "In",
    name: "Indium",
    category: "post-transition",
    block: "p",
    row: 5,
    col: 13,
  },
  {
    symbol: "Sn",
    name: "Tin",
    category: "post-transition",
    block: "p",
    row: 5,
    col: 14,
  },
  {
    symbol: "Sb",
    name: "Antimony",
    category: "metalloid",
    block: "p",
    row: 5,
    col: 15,
  },
  {
    symbol: "Te",
    name: "Tellurium",
    category: "metalloid",
    block: "p",
    row: 5,
    col: 16,
  },
  {
    symbol: "I",
    name: "Iodine",
    category: "halogen",
    block: "p",
    row: 5,
    col: 17,
  },
  {
    symbol: "Xe",
    name: "Xenon",
    category: "noble-gas",
    block: "p",
    row: 5,
    col: 18,
  },
  // Period 6
  {
    symbol: "Cs",
    name: "Caesium",
    category: "alkaline",
    block: "s",
    row: 6,
    col: 1,
  },
  {
    symbol: "Ba",
    name: "Barium",
    category: "alkaline-earth",
    block: "s",
    row: 6,
    col: 2,
  },
  {
    symbol: "La",
    name: "Lanthanum",
    category: "lanthanide",
    block: "f",
    row: 6,
    col: 3,
  },
  {
    symbol: "Hf",
    name: "Hafnium",
    category: "transition",
    block: "d",
    row: 6,
    col: 4,
  },
  {
    symbol: "Ta",
    name: "Tantalum",
    category: "transition",
    block: "d",
    row: 6,
    col: 5,
  },
  {
    symbol: "W",
    name: "Tungsten",
    category: "transition",
    block: "d",
    row: 6,
    col: 6,
  },
  {
    symbol: "Re",
    name: "Rhenium",
    category: "transition",
    block: "d",
    row: 6,
    col: 7,
  },
  {
    symbol: "Os",
    name: "Osmium",
    category: "transition",
    block: "d",
    row: 6,
    col: 8,
  },
  {
    symbol: "Ir",
    name: "Iridium",
    category: "transition",
    block: "d",
    row: 6,
    col: 9,
  },
  {
    symbol: "Pt",
    name: "Platinum",
    category: "transition",
    block: "d",
    row: 6,
    col: 10,
  },
  {
    symbol: "Au",
    name: "Gold",
    category: "transition",
    block: "d",
    row: 6,
    col: 11,
  },
  {
    symbol: "Hg",
    name: "Mercury",
    category: "transition",
    block: "d",
    row: 6,
    col: 12,
  },
  {
    symbol: "Tl",
    name: "Thallium",
    category: "post-transition",
    block: "p",
    row: 6,
    col: 13,
  },
  {
    symbol: "Pb",
    name: "Lead",
    category: "post-transition",
    block: "p",
    row: 6,
    col: 14,
  },
  {
    symbol: "Bi",
    name: "Bismuth",
    category: "post-transition",
    block: "p",
    row: 6,
    col: 15,
  },
  {
    symbol: "Po",
    name: "Polonium",
    category: "metalloid",
    block: "p",
    row: 6,
    col: 16,
  },
  {
    symbol: "At",
    name: "Astatine",
    category: "halogen",
    block: "p",
    row: 6,
    col: 17,
  },
  {
    symbol: "Rn",
    name: "Radon",
    category: "noble-gas",
    block: "p",
    row: 6,
    col: 18,
  },
  // Lanthanides (f-block, displayed in row 8)
  {
    symbol: "Ce",
    name: "Cerium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 4,
  },
  {
    symbol: "Pr",
    name: "Praseodymium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 5,
  },
  {
    symbol: "Nd",
    name: "Neodymium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 6,
  },
  {
    symbol: "Pm",
    name: "Promethium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 7,
  },
  {
    symbol: "Sm",
    name: "Samarium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 8,
  },
  {
    symbol: "Eu",
    name: "Europium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 9,
  },
  {
    symbol: "Gd",
    name: "Gadolinium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 10,
  },
  {
    symbol: "Tb",
    name: "Terbium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 11,
  },
  {
    symbol: "Dy",
    name: "Dysprosium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 12,
  },
  {
    symbol: "Ho",
    name: "Holmium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 13,
  },
  {
    symbol: "Er",
    name: "Erbium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 14,
  },
  {
    symbol: "Tm",
    name: "Thulium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 15,
  },
  {
    symbol: "Yb",
    name: "Ytterbium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 16,
  },
  {
    symbol: "Lu",
    name: "Lutetium",
    category: "lanthanide",
    block: "f",
    row: 8,
    col: 17,
  },
  // Period 7
  {
    symbol: "Fr",
    name: "Francium",
    category: "alkaline",
    block: "s",
    row: 7,
    col: 1,
  },
  {
    symbol: "Ra",
    name: "Radium",
    category: "alkaline-earth",
    block: "s",
    row: 7,
    col: 2,
  },
  {
    symbol: "Ac",
    name: "Actinium",
    category: "actinide",
    block: "f",
    row: 7,
    col: 3,
  },
  {
    symbol: "Rf",
    name: "Rutherfordium",
    category: "transition",
    block: "d",
    row: 7,
    col: 4,
  },
  {
    symbol: "Db",
    name: "Dubnium",
    category: "transition",
    block: "d",
    row: 7,
    col: 5,
  },
  {
    symbol: "Sg",
    name: "Seaborgium",
    category: "transition",
    block: "d",
    row: 7,
    col: 6,
  },
  {
    symbol: "Bh",
    name: "Bohrium",
    category: "transition",
    block: "d",
    row: 7,
    col: 7,
  },
  {
    symbol: "Hs",
    name: "Hassium",
    category: "transition",
    block: "d",
    row: 7,
    col: 8,
  },
  {
    symbol: "Mt",
    name: "Meitnerium",
    category: "transition",
    block: "d",
    row: 7,
    col: 9,
  },
  {
    symbol: "Ds",
    name: "Darmstadtium",
    category: "transition",
    block: "d",
    row: 7,
    col: 10,
  },
  {
    symbol: "Rg",
    name: "Roentgenium",
    category: "transition",
    block: "d",
    row: 7,
    col: 11,
  },
  {
    symbol: "Cn",
    name: "Copernicium",
    category: "transition",
    block: "d",
    row: 7,
    col: 12,
  },
  {
    symbol: "Nh",
    name: "Nihonium",
    category: "post-transition",
    block: "p",
    row: 7,
    col: 13,
  },
  {
    symbol: "Fl",
    name: "Flerovium",
    category: "post-transition",
    block: "p",
    row: 7,
    col: 14,
  },
  {
    symbol: "Mc",
    name: "Moscovium",
    category: "post-transition",
    block: "p",
    row: 7,
    col: 15,
  },
  {
    symbol: "Lv",
    name: "Livermorium",
    category: "post-transition",
    block: "p",
    row: 7,
    col: 16,
  },
  {
    symbol: "Ts",
    name: "Tennessine",
    category: "halogen",
    block: "p",
    row: 7,
    col: 17,
  },
  {
    symbol: "Og",
    name: "Oganesson",
    category: "noble-gas",
    block: "p",
    row: 7,
    col: 18,
  },
  // Actinides (f-block, displayed in row 9)
  {
    symbol: "Th",
    name: "Thorium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 4,
  },
  {
    symbol: "Pa",
    name: "Protactinium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 5,
  },
  {
    symbol: "U",
    name: "Uranium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 6,
  },
  {
    symbol: "Np",
    name: "Neptunium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 7,
  },
  {
    symbol: "Pu",
    name: "Plutonium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 8,
  },
  {
    symbol: "Am",
    name: "Americium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 9,
  },
  {
    symbol: "Cm",
    name: "Curium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 10,
  },
  {
    symbol: "Bk",
    name: "Berkelium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 11,
  },
  {
    symbol: "Cf",
    name: "Californium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 12,
  },
  {
    symbol: "Es",
    name: "Einsteinium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 13,
  },
  {
    symbol: "Fm",
    name: "Fermium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 14,
  },
  {
    symbol: "Md",
    name: "Mendelevium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 15,
  },
  {
    symbol: "No",
    name: "Nobelium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 16,
  },
  {
    symbol: "Lr",
    name: "Lawrencium",
    category: "actinide",
    block: "f",
    row: 9,
    col: 17,
  },
];

export const colors: Record<PeriodicCategory, { bg: string; text: string }> = {
  nonmetal: { bg: "bg-blue-100", text: "text-blue-800" },
  "noble-gas": { bg: "bg-purple-200", text: "text-purple-900" },
  alkaline: { bg: "bg-red-100", text: "text-red-800" },
  "alkaline-earth": { bg: "bg-orange-100", text: "text-orange-800" },
  "post-transition": { bg: "bg-green-100", text: "text-green-800" },
  metalloid: { bg: "bg-cyan-100", text: "text-cyan-800" },
  halogen: { bg: "bg-purple-100", text: "text-purple-800" },
  transition: { bg: "bg-yellow-100", text: "text-yellow-800" },
  lanthanide: { bg: "bg-amber-50", text: "text-amber-700" },
  actinide: { bg: "bg-stone-100", text: "text-stone-700" },
};

export const labels: Record<PeriodicCategory, string> = {
  nonmetal: "Nonmetal",
  "noble-gas": "Noble Gas",
  alkaline: "Alkali Metal",
  "alkaline-earth": "Alkaline Earth Metal",
  "post-transition": "Post-transition Metal",
  metalloid: "Metalloid",
  halogen: "Halogen",
  transition: "Transition Metal",
  lanthanide: "Lanthanide",
  actinide: "Actinide",
};
